# Generated by Django 5.0.7 on 2024-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelDeControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despliegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desplegada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
