# Generated by Django 5.0.7 on 2024-07-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanelDeControl', '0002_despliegue_alter_tarea_completada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despliegue',
            options={'verbose_name': 'despliegue', 'verbose_name_plural': 'despliegues'},
        ),
    ]
