# Generated by Django 5.0.7 on 2024-07-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelDeControl', '0003_alter_despliegue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegue',
            name='ruta_despliegue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='despliegue',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
